services:
  manager:
    image: ${PROXY_IMAGE:-proxy}
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${MANAGER_PORT:-8088}:80"
    volumes:
      - ${MANAGER_DB_PATH:-/var/lib/ace-ytdlp-manager/manager-data/}:/app/data
    restart: ${RESTART_POLICY:-always}

  acestream:
    image: ghcr.io/martinbjeldbak/acestream-http-proxy
    ports:
      - "0.0.0.0:${ACE_PORT:-6878}:6878"
    volumes:
      - ${ACESTREAM_CACHE_PATH:-/var/lib/ace-ytdlp-manager/acestream-cache/}:/home/appuser/.ACEStream/
    environment:
      - ALLOW_REMOTE_ACCESS=yes
      - EXTRA_FLAGS= --cache-limit 1
    restart: ${RESTART_POLICY_ACELINK:-always}

  acexy:
    image: ghcr.io/javinator9889/acexy:0.2.2
    restart: unless-stopped
    ports:
      - ${ACEXY_PORT:-8090}:80/tcp
    environment:
      ACEXY_LISTEN_ADDR: ":80"              # Listen on port 80
      ACEXY_SCHEME: "http"                  # Use HTTP
      ACEXY_HOST: "acestream"               # Host is "acestream" or the name of the AceStream service
      ACEXY_PORT: "6878"                    # Port is 6878
      ACEXY_M3U8_STREAM_TIMEOUT: "60s"      # Timeout is 60 seconds when in M3U8 mode
      ACEXY_M3U8: "false"                   # Disable M3U8 mode
      ACEXY_EMPTY_TIMEOUT: "60s"            # Timeout to close the connection if no data is received
      ACEXY_BUFFER_SIZE: 4MB                # Buffer size is 4MB
      ACEXY_NO_RESPONSE_TIMEOUT: "10s"      # Timeout to close the connection if no response is received
      ACEXY_CLIENT_EVICTION_TIMEOUT: "5s"   # Timeout to evict clients that are not responding
    links:
      - acestream
    depends_on:
      - acestream

